apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - name: train
        image: gabiiiiii14258/train-service:latest
        ports:
        - containerPort: 5000